---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  version: default
  deployment:
    cluster_wide_access: true
    accessible_namespaces:
      - "**"
    namespace: istio-system
    pod_labels:
      sidecar.istio.io/inject: 'false'
  auth:
    strategy: openshift
  external_services:
    grafana:
      enabled: false
    prometheus:
      auth:
        type: bearer
        use_kiali_token: true
      thanos_proxy:
        enabled: true
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
    # tracing:
    #   enabled: true
    #   internal_url: "http://tempo-sample-query-frontend.tracing-system.svc.cluster.local:3200"
    #   external_url: ${JAEGERROUTE} 
    #   query_timeout: 60
    #   use_grpc: false
    #   provider: tempo
    #   tempo_config:
    #     url_format: "jaeger"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-monitoring-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: kiali-service-account
  namespace: istio-system