apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: webstore-waypoint
  namespace: webstore
  labels:
    istio.io/waypoint-for: all
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: ALL

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webstore-waypoint-impersonator
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts/impersonate"]
  verbs: ["impersonate"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webstore-waypoint-impersonation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webstore-waypoint-impersonator
subjects:
- kind: ServiceAccount
  name: webstore-waypoint
  namespace: webstore
