apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: webstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        version: "alpine"
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: webstore
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    app: redis

---
apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: redis-service-monitor
  namespace: webstore
  labels:
    release: prometheus-operator
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      app: redis
  endpoints:
  - port: redis
    interval: 30s