apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-sa
  namespace: webstore

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-sa-waypoint-impersonation
  namespace: webstore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webstore-waypoint-impersonator
subjects:
- kind: ServiceAccount
  name: user-sa
  namespace: webstore

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: webstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
        version: "1.0"
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: user-sa
      containers:
      - name: user
        image: quay.io/rh_rh/ossm3-user:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: "redis"
        ports:
        - containerPort: 6000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: webstore
spec:
  ports:
  - port: 80
    name: http
    targetPort: 6000
  selector:
    app: user

---
apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: user-service-monitor
  namespace: webstore
  labels:
    release: prometheus-operator
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      app: user
  endpoints:
  - port: http
    path: /metrics
    interval: 30s

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: user-ingress
  namespace: webstore
spec:
  to:
    kind: Service
    name: user-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
  namespace: webstore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: user-route
  namespace: webstore
spec:
  parentRefs:
  - name: external-gateway
    namespace: istio-system
  hostnames:
  - "user-service"
  - "*.apps.cluster-qm7sq.qm7sq.sandbox3406.opentlc.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /users
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: user-service
      port: 80