apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  labels:
    app: webstore
  name: monitoring-stack
  namespace: istio-system
spec:
  logLevel: debug
  retention: 3d
  resourceSelector:
    matchLabels:
      app: webstore

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus
  namespace: istio-system
spec:
  to:
    kind: Service
    name: monitoring-stack-prometheus
    weight: 100
  port:
    targetPort: 9090
  tls:
    termination: edge
