kind: IstioCNI
apiVersion: sailoperator.io/v1
metadata:
  name: default
spec:
  namespace: istio-system
  profile: ambient
  values:
    cni:
      ambient:
        reconcileIptablesOnStartup: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: maistra.io/exclude-cni
                operator: NotIn
                values:
                - "true"
  version: v1.27.3
