kind: Namespace
apiVersion: v1
metadata:
  name: ztunnel
  labels:
    istio-discovery: enabled

---
apiVersion: sailoperator.io/v1
kind: ZTunnel
metadata:
  name: default
spec:
  namespace: ztunnel
  profile: ambient
  values:
    ztunnel:
      nodeSelector:
        maistra.io/exclude-ztunnel: "false"
      logLevel: info
      terminationGracePeriodSeconds: 30
  version: v1.27.3
