FROM python:3.10-slim

WORKDIR /app

RUN \
    apt update && \
    apt install -y \
        curl

COPY requirements.txt .

RUN \
    pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 6000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "6000"]